version: "3.9"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  weatherapi:
    image: "glaptev8/weatherapi:v0.0"
    environment:
      SPRING_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/postgres"
      LIQUIBASE_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - postgres